version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: bsm_postgres
    restart: always
    environment:
      POSTGRES_USER: bsm_user
      POSTGRES_PASSWORD: bsm_password
      POSTGRES_DB: bsm_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./scripts/schema.sql:/docker-entrypoint-initdb.d/schema.sql

  redis:
    image: redis:7-alpine
    container_name: bsm_redis
    restart: always
    ports:
      - "6379:6379"

  rabbitmq:
    image: rabbitmq:3.13-management-alpine
    container_name: bsm_rabbitmq
    restart: always
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    ports:
      - "5672:5672"
      - "15672:15672"

volumes:
  pgdata:
